export type Oil = {
  id: string;
  name: string;
  category: 'essential' | 'carrier' | 'scf';
  shortDescription: string;
  benefits: string[];
  imageHint: string;
};

export const products: Oil[] = [
  // Essential Oils
  {
    id: 'essential-1',
    name: 'Mentha Arvensis',
    category: 'essential',
    shortDescription: 'Refreshing and invigorating aroma.',
    benefits: ['Perfect for aromatherapy', 'Ideal for personal care products', 'Also known as Menthol Mint'],
    imageHint: 'mint leaves',
  },
  {
    id: 'essential-2',
    name: 'Peppermint Oil',
    category: 'essential',
    shortDescription: 'Cool, minty essence.',
    benefits: ['Relief from itching, muscle pain, and headache', 'Flavoring agent in foods and mouthwash', 'Fresh scent for soaps and cosmetics'],
    imageHint: 'peppermint leaves',
  },
  {
    id: 'essential-3',
    name: 'Spearmint Oil',
    category: 'essential',
    shortDescription: 'Sweet, gentle fragrance.',
    benefits: ['Good for digestive upsets', 'High in antioxidants', 'Fights bacterial infections', 'Improves arthritis pain'],
    imageHint: 'spearmint plant',
  },
  {
    id: 'essential-4',
    name: 'Lemongrass Oil',
    category: 'essential',
    shortDescription: 'Citrusy delight, uplifting scent.',
    benefits: ['Antibacterial and antifungal properties', 'Anti-inflammatory benefits', 'Prevents ulcers and relieves nausea'],
    imageHint: 'lemongrass stalk',
  },
  {
    id: 'essential-5',
    name: 'Palmarosa Oil',
    category: 'essential',
    shortDescription: 'Delicate floral aroma.',
    benefits: ['Hydrates and balances skin', 'Supports relaxation', 'Reduces stress and anxiety', 'Natural antibacterial properties'],
    imageHint: 'pink flowers',
  },
  {
    id: 'essential-6',
    name: 'Citronella Oil',
    category: 'essential',
    shortDescription: 'Natural insect repellent.',
    benefits: ['Effective insect repellent', 'Antifungal and promotes wound healing', 'Mood-lifting and relieves fatigue'],
    imageHint: 'citronella grass',
  },
  {
    id: 'essential-7',
    name: 'Vetiver Oil',
    category: 'essential',
    shortDescription: 'Earthy, grounding aroma.',
    benefits: ['Promotes alertness', 'Aids breathing during sleep', 'Contains antioxidants', 'Calming and stabilizing properties'],
    imageHint: 'vetiver grass',
  },
  {
    id: 'essential-8',
    name: 'Geranium Oil',
    category: 'essential',
    shortDescription: 'Floral elegance, balancing qualities.',
    benefits: ['Relieves anxiety, depression, and insomnia', 'Balances hormones', 'Improves complexion'],
    imageHint: 'geranium flower',
  },
  {
    id: 'essential-9',
    name: 'Basil Oil',
    category: 'essential',
    shortDescription: 'Cleansing and purifying.',
    benefits: ['Cleanses the skin', 'Treats acne and skin diseases', 'Promotes hair growth'],
    imageHint: 'basil leaves',
  },
  {
    id: 'essential-10',
    name: 'Eucalyptus Oil',
    category: 'essential',
    shortDescription: 'Clears and eases breathing.',
    benefits: ['Relieves stuffy nose', 'Clears respiratory complaints', 'Eases sore muscles and joints', 'Post-surgery pain relief'],
    imageHint: 'eucalyptus leaves',
  },
  {
    id: 'essential-11',
    name: 'Rosemary Oil',
    category: 'essential',
    shortDescription: 'Herbaceous and energizing.',
    benefits: ['Antimicrobial properties', 'Anti-inflammatory effects', 'Rich in antioxidants'],
    imageHint: 'rosemary sprig',
  },
  {
    id: 'essential-12',
    name: 'Caraway Oil',
    category: 'essential',
    shortDescription: 'Spicy and warming.',
    benefits: ['Reduces inflammation', 'Encourages digestion', 'Promotes weight loss'],
    imageHint: 'caraway seeds',
  },
  {
    id: 'essential-13',
    name: 'Anise Oil',
    category: 'essential',
    shortDescription: 'Sweet and licorice-like.',
    benefits: ['Helps breathing', 'Relieves pain', 'Eases thirst'],
    imageHint: 'star anise',
  },
  {
    id: 'essential-14',
    name: 'Blackpepper Oil',
    category: 'essential',
    shortDescription: 'Spicy and stimulating.',
    benefits: ['Relieves aches and pains', 'Lowers blood pressure', 'Has anti-virulence properties'],
    imageHint: 'black peppercorns',
  },
  {
    id: 'essential-15',
    name: 'Tea Tree Oil',
    category: 'essential',
    shortDescription: 'Medicinal and fresh.',
    benefits: ['Promotes glowing skin', 'Treats acne and infections', 'Prevents dandruff and lice'],
    imageHint: 'tea tree',
  },
  
  // Carrier Oils
  {
    id: 'carrier-1',
    name: 'Blackseed Oil',
    category: 'carrier',
    shortDescription: 'Treats pain and infections.',
    benefits: ['Treats headaches and back pain', 'Reduces inflammation', 'Regulates high blood pressure'],
    imageHint: 'black seeds',
  },
  {
    id: 'carrier-2',
    name: 'Rosehip Seed Oil',
    category: 'carrier',
    shortDescription: 'Corrects and fades skin imperfections.',
    benefits: ['Corrects dark spots', 'Fights acne', 'Fades scars'],
    imageHint: 'rose hips',
  },
  {
    id: 'carrier-3',
    name: 'Jojoba Oil',
    category: 'carrier',
    shortDescription: 'Restores skin and hair.',
    benefits: ['Treats dry skin and acne', 'Reduces inflammation', 'Restores damaged hair'],
    imageHint: 'jojoba nuts',
  },
  {
    id: 'carrier-4',
    name: 'Sesame Oil',
    category: 'carrier',
    shortDescription: 'Nourishing and protective.',
    benefits: ['Regulates blood sugar', 'Improves hair health', 'Relieves stress', 'Protects from sun damage'],
    imageHint: 'sesame seeds',
  },

  // SCF CO2 Oils & Oleoresins
  {
    id: 'scf-1',
    name: 'Ginger Oil',
    category: 'scf',
    shortDescription: 'Warming and rejuvenating.',
    benefits: ['Stress relief and rejuvenation', 'Supports better digestion', 'Improves skin condition'],
    imageHint: 'ginger root',
  },
  {
    id: 'scf-2',
    name: 'Saw Palmetto Oil',
    category: 'scf',
    shortDescription: 'Supports urinary and hair health.',
    benefits: ['Prevents hair loss', 'Improves urinary and prostate health', 'Regulates testosterone'],
    imageHint: 'saw palmetto',
  },
  {
    id: 'scf-3',
    name: 'Fenugreek Seed Oil',
    category: 'scf',
    shortDescription: 'Regulates and relieves.',
    benefits: ['Lowers blood sugar', 'Regulates cholesterol', 'Relieves cramps', 'Raises testosterone'],
    imageHint: 'fenugreek seeds',
  },
  {
    id: 'scf-4',
    name: 'Capsicum Oleoresin',
    category: 'scf',
    shortDescription: 'Metabolism-boosting and rich in vitamins.',
    benefits: ['Boosts metabolism', 'Rich in vitamins C & A', 'Used for asthma, cataracts, arthritis'],
    imageHint: 'chili peppers',
  },
  {
    id: 'scf-5',
    name: 'Turmeric Oil',
    category: 'scf',
    shortDescription: 'Anti-inflammatory and clarifying.',
    benefits: ['Antioxidant and anti-inflammatory', 'Skin clarity, radiant complexion', 'Mood uplifting'],
    imageHint: 'turmeric root',
  },
  {
    id: 'scf-6',
    name: 'Paprika Oleoresin',
    category: 'scf',
    shortDescription: 'Rich color and health benefits.',
    benefits: ['Reduces inflammation', 'Improves cholesterol', 'Controls blood sugar', 'Anticancer effects'],
    imageHint: 'paprika powder',
  },
];
